
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.chromatic.mod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.chromatic.mod.block.YellowSmallInvertedBricksBlock;
import net.chromatic.mod.block.YellowSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.YellowSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.YellowSmallChromaBricksBlock;
import net.chromatic.mod.block.YellowSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.YellowSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.YellowInvertedTileBlock;
import net.chromatic.mod.block.YellowInvertedStairsBlock;
import net.chromatic.mod.block.YellowInvertedSlabBlock;
import net.chromatic.mod.block.YellowInvertedBricksBlock;
import net.chromatic.mod.block.YellowInvertedBrickStairsBlock;
import net.chromatic.mod.block.YellowInvertedBrickSlabBlock;
import net.chromatic.mod.block.YellowCutInvertedTileBlock;
import net.chromatic.mod.block.YellowCutInvertedStairsBlock;
import net.chromatic.mod.block.YellowCutInvertedSlabBlock;
import net.chromatic.mod.block.YellowCutChromaTileBlock;
import net.chromatic.mod.block.YellowCutChromaStairsBlock;
import net.chromatic.mod.block.YellowCutChromaSlabBlock;
import net.chromatic.mod.block.YellowChromaTileBlock;
import net.chromatic.mod.block.YellowChromaStairsBlock;
import net.chromatic.mod.block.YellowChromaSlabBlock;
import net.chromatic.mod.block.YellowChromaBricksBlock;
import net.chromatic.mod.block.YellowChromaBrickStairsBlock;
import net.chromatic.mod.block.YellowChromaBrickSlabBlock;
import net.chromatic.mod.block.SmallInvertedBricksBlock;
import net.chromatic.mod.block.SmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.SmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.SmallChromaBricksBlock;
import net.chromatic.mod.block.SmallChromaBrickStairsBlock;
import net.chromatic.mod.block.SmallChromaBrickSlabBlock;
import net.chromatic.mod.block.RedSmallInvertedBricksBlock;
import net.chromatic.mod.block.RedSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.RedSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.RedSmallChromaBricksBlock;
import net.chromatic.mod.block.RedSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.RedSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.RedInvertedTileBlock;
import net.chromatic.mod.block.RedInvertedStairsBlock;
import net.chromatic.mod.block.RedInvertedSlabBlock;
import net.chromatic.mod.block.RedInvertedBricksBlock;
import net.chromatic.mod.block.RedInvertedBrickStairsBlock;
import net.chromatic.mod.block.RedInvertedBrickSlabBlock;
import net.chromatic.mod.block.RedCutInvertedTileBlock;
import net.chromatic.mod.block.RedCutInvertedStairsBlock;
import net.chromatic.mod.block.RedCutInvertedSlabBlock;
import net.chromatic.mod.block.RedCutChromaTileBlock;
import net.chromatic.mod.block.RedCutChromaStairsBlock;
import net.chromatic.mod.block.RedCutChromaSlabBlock;
import net.chromatic.mod.block.RedChromaTileBlock;
import net.chromatic.mod.block.RedChromaStairsBlock;
import net.chromatic.mod.block.RedChromaSlabBlock;
import net.chromatic.mod.block.RedChromaBricksBlock;
import net.chromatic.mod.block.RedChromaBrickStairsBlock;
import net.chromatic.mod.block.RedChromaBrickSlabBlock;
import net.chromatic.mod.block.PurpleSmallInvertedBricksBlock;
import net.chromatic.mod.block.PurpleSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.PurpleSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.PurpleSmallChromaBricksBlock;
import net.chromatic.mod.block.PurpleSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.PurpleSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.PurpleInvertedTileBlock;
import net.chromatic.mod.block.PurpleInvertedStairsBlock;
import net.chromatic.mod.block.PurpleInvertedSlabBlock;
import net.chromatic.mod.block.PurpleInvertedBricksBlock;
import net.chromatic.mod.block.PurpleInvertedBrickStairsBlock;
import net.chromatic.mod.block.PurpleInvertedBrickSlabBlock;
import net.chromatic.mod.block.PurpleCutInvertedTileBlock;
import net.chromatic.mod.block.PurpleCutInvertedStairsBlock;
import net.chromatic.mod.block.PurpleCutInvertedSlabBlock;
import net.chromatic.mod.block.PurpleCutChromaTileBlock;
import net.chromatic.mod.block.PurpleCutChromaStairsBlock;
import net.chromatic.mod.block.PurpleCutChromaSlabBlock;
import net.chromatic.mod.block.PurpleChromaTileBlock;
import net.chromatic.mod.block.PurpleChromaStairsBlock;
import net.chromatic.mod.block.PurpleChromaSlabBlock;
import net.chromatic.mod.block.PurpleChromaBricksBlock;
import net.chromatic.mod.block.PurpleChromaBrickStairsBlock;
import net.chromatic.mod.block.PurpleChromaBrickSlabBlock;
import net.chromatic.mod.block.PinkSmallInvertedBricksBlock;
import net.chromatic.mod.block.PinkSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.PinkSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.PinkSmallChromaBricksBlock;
import net.chromatic.mod.block.PinkSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.PinkSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.PinkInvertedTileBlock;
import net.chromatic.mod.block.PinkInvertedStairsBlock;
import net.chromatic.mod.block.PinkInvertedSlabBlock;
import net.chromatic.mod.block.PinkInvertedBricksBlock;
import net.chromatic.mod.block.PinkInvertedBrickStairsBlock;
import net.chromatic.mod.block.PinkInvertedBrickSlabBlock;
import net.chromatic.mod.block.PinkCutInvertedTileBlock;
import net.chromatic.mod.block.PinkCutInvertedStairsBlock;
import net.chromatic.mod.block.PinkCutInvertedSlabBlock;
import net.chromatic.mod.block.PinkCutChromaTileBlock;
import net.chromatic.mod.block.PinkCutChromaStairsBlock;
import net.chromatic.mod.block.PinkCutChromaSlabBlock;
import net.chromatic.mod.block.PinkChromaTileBlock;
import net.chromatic.mod.block.PinkChromaStairsBlock;
import net.chromatic.mod.block.PinkChromaSlabBlock;
import net.chromatic.mod.block.PinkChromaBricksBlock;
import net.chromatic.mod.block.PinkChromaBrickStairsBlock;
import net.chromatic.mod.block.PinkChromaBrickSlabBlock;
import net.chromatic.mod.block.OrangeSmallInvertedBricksBlock;
import net.chromatic.mod.block.OrangeSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.OrangeSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.OrangeSmallChromaBricksBlock;
import net.chromatic.mod.block.OrangeSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.OrangeSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.OrangeInvertedTileBlock;
import net.chromatic.mod.block.OrangeInvertedStairsBlock;
import net.chromatic.mod.block.OrangeInvertedSlabBlock;
import net.chromatic.mod.block.OrangeInvertedBricksBlock;
import net.chromatic.mod.block.OrangeInvertedBrickStairsBlock;
import net.chromatic.mod.block.OrangeInvertedBrickSlabBlock;
import net.chromatic.mod.block.OrangeCutInvertedTileBlock;
import net.chromatic.mod.block.OrangeCutInvertedStairsBlock;
import net.chromatic.mod.block.OrangeCutInvertedSlabBlock;
import net.chromatic.mod.block.OrangeCutChromaTileBlock;
import net.chromatic.mod.block.OrangeCutChromaStairsBlock;
import net.chromatic.mod.block.OrangeCutChromaSlabBlock;
import net.chromatic.mod.block.OrangeChromaTileBlock;
import net.chromatic.mod.block.OrangeChromaStairsBlock;
import net.chromatic.mod.block.OrangeChromaSlabBlock;
import net.chromatic.mod.block.OrangeChromaBricksBlock;
import net.chromatic.mod.block.OrangeChromaBrickStairsBlock;
import net.chromatic.mod.block.OrangeChromaBrickSlabBlock;
import net.chromatic.mod.block.MagenteCutInvertedTileBlock;
import net.chromatic.mod.block.MagentaSmallInvertedBricksBlock;
import net.chromatic.mod.block.MagentaSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.MagentaSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.MagentaSmallChromaBricksBlock;
import net.chromatic.mod.block.MagentaSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.MagentaSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.MagentaInvertedTileBlock;
import net.chromatic.mod.block.MagentaInvertedStairsBlock;
import net.chromatic.mod.block.MagentaInvertedSlabBlock;
import net.chromatic.mod.block.MagentaInvertedBricksBlock;
import net.chromatic.mod.block.MagentaInvertedBrickStairsBlock;
import net.chromatic.mod.block.MagentaInvertedBrickSlabBlock;
import net.chromatic.mod.block.MagentaCutInvertedStairsBlock;
import net.chromatic.mod.block.MagentaCutInvertedSlabBlock;
import net.chromatic.mod.block.MagentaCutChromaTileBlock;
import net.chromatic.mod.block.MagentaCutChromaStairsBlock;
import net.chromatic.mod.block.MagentaCutChromaSlabBlock;
import net.chromatic.mod.block.MagentaChromaTileBlock;
import net.chromatic.mod.block.MagentaChromaStairsBlock;
import net.chromatic.mod.block.MagentaChromaSlabBlock;
import net.chromatic.mod.block.MagentaChromaBricksBlock;
import net.chromatic.mod.block.MagentaChromaBrickStairsBlock;
import net.chromatic.mod.block.MagentaChromaBrickSlabBlock;
import net.chromatic.mod.block.InvertedTileBlock;
import net.chromatic.mod.block.InvertedStairsBlock;
import net.chromatic.mod.block.InvertedSlabBlock;
import net.chromatic.mod.block.InvertedBricksBlock;
import net.chromatic.mod.block.InvertedBrickStairsBlock;
import net.chromatic.mod.block.InvertedBrickSlabBlock;
import net.chromatic.mod.block.GreenSmallInvertedBricksBlock;
import net.chromatic.mod.block.GreenSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.GreenSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.GreenSmallChromaBricksBlock;
import net.chromatic.mod.block.GreenSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.GreenSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.GreenInvertedTileBlock;
import net.chromatic.mod.block.GreenInvertedStairsBlock;
import net.chromatic.mod.block.GreenInvertedSlabBlock;
import net.chromatic.mod.block.GreenInvertedBricksBlock;
import net.chromatic.mod.block.GreenInvertedBrickStairsBlock;
import net.chromatic.mod.block.GreenInvertedBrickSlabBlock;
import net.chromatic.mod.block.GreenCutInvertedTileBlock;
import net.chromatic.mod.block.GreenCutInvertedStairsBlock;
import net.chromatic.mod.block.GreenCutInvertedSlabBlock;
import net.chromatic.mod.block.GreenCutChromaTileBlock;
import net.chromatic.mod.block.GreenCutChromaStairsBlock;
import net.chromatic.mod.block.GreenCutChromaSlabBlock;
import net.chromatic.mod.block.GreenChromaTileBlock;
import net.chromatic.mod.block.GreenChromaStairsBlock;
import net.chromatic.mod.block.GreenChromaSlabBlock;
import net.chromatic.mod.block.GreenChromaBricksBlock;
import net.chromatic.mod.block.GreenChromaBrickStairsBlock;
import net.chromatic.mod.block.GreenChromaBrickSlabBlock;
import net.chromatic.mod.block.GraySmallInvertedBricksBlock;
import net.chromatic.mod.block.GraySmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.GraySmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.GraySmallChromaBricksBlock;
import net.chromatic.mod.block.GraySmallChromaBrickStairsBlock;
import net.chromatic.mod.block.GraySmallChromaBrickSlabBlock;
import net.chromatic.mod.block.GrayInvertedTileBlock;
import net.chromatic.mod.block.GrayInvertedStairsBlock;
import net.chromatic.mod.block.GrayInvertedSlabBlock;
import net.chromatic.mod.block.GrayInvertedBricksBlock;
import net.chromatic.mod.block.GrayInvertedBrickStairsBlock;
import net.chromatic.mod.block.GrayInvertedBrickSlabBlock;
import net.chromatic.mod.block.GrayCutInvertedTileBlock;
import net.chromatic.mod.block.GrayCutInvertedStairsBlock;
import net.chromatic.mod.block.GrayCutInvertedSlabBlock;
import net.chromatic.mod.block.GrayCutChromaTileBlock;
import net.chromatic.mod.block.GrayCutChromaStairsBlock;
import net.chromatic.mod.block.GrayCutChromaSlabBlock;
import net.chromatic.mod.block.GrayChromaTileBlock;
import net.chromatic.mod.block.GrayChromaStairsBlock;
import net.chromatic.mod.block.GrayChromaSlabBlock;
import net.chromatic.mod.block.GrayChromaBricksBlock;
import net.chromatic.mod.block.GrayChromaBrickStairsBlock;
import net.chromatic.mod.block.GrayChromaBrickSlabBlock;
import net.chromatic.mod.block.CyanSmallInvertedBricksBlock;
import net.chromatic.mod.block.CyanSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.CyanSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.CyanSmallChromaBricksBlock;
import net.chromatic.mod.block.CyanSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.CyanSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.CyanInvertedTileBlock;
import net.chromatic.mod.block.CyanInvertedStairsBlock;
import net.chromatic.mod.block.CyanInvertedSlabBlock;
import net.chromatic.mod.block.CyanInvertedBricksBlock;
import net.chromatic.mod.block.CyanInvertedBrickStairsBlock;
import net.chromatic.mod.block.CyanInvertedBrickSlabBlock;
import net.chromatic.mod.block.CyanCutInvertedTileBlock;
import net.chromatic.mod.block.CyanCutInvertedStairsBlock;
import net.chromatic.mod.block.CyanCutInvertedSlabBlock;
import net.chromatic.mod.block.CyanCutChromaTileBlock;
import net.chromatic.mod.block.CyanCutChromaStairsBlock;
import net.chromatic.mod.block.CyanCutChromaSlabBlock;
import net.chromatic.mod.block.CyanChromaTileBlock;
import net.chromatic.mod.block.CyanChromaStairsBlock;
import net.chromatic.mod.block.CyanChromaSlabBlock;
import net.chromatic.mod.block.CyanChromaBricksBlock;
import net.chromatic.mod.block.CyanChromaBrickStairsBlock;
import net.chromatic.mod.block.CyanChromaBrickSlabBlock;
import net.chromatic.mod.block.CutInvertedTileBlock;
import net.chromatic.mod.block.CutInvertedStairsBlock;
import net.chromatic.mod.block.CutInvertedSlabBlock;
import net.chromatic.mod.block.CutChromaTileBlock;
import net.chromatic.mod.block.CutChromaStairsBlock;
import net.chromatic.mod.block.CutChromaSlabBlock;
import net.chromatic.mod.block.ChromaTileBlock;
import net.chromatic.mod.block.ChromaStairsBlock;
import net.chromatic.mod.block.ChromaSlabBlock;
import net.chromatic.mod.block.ChromaBricksBlock;
import net.chromatic.mod.block.ChromaBrickStairsBlock;
import net.chromatic.mod.block.ChromaBrickSlabBlock;
import net.chromatic.mod.block.BrownSmallInvertedBricksBlock;
import net.chromatic.mod.block.BrownSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.BrownSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.BrownSmallChromaBricksBlock;
import net.chromatic.mod.block.BrownSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.BrownSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.BrownInvertedTileBlock;
import net.chromatic.mod.block.BrownInvertedStairsBlock;
import net.chromatic.mod.block.BrownInvertedSlabBlock;
import net.chromatic.mod.block.BrownInvertedBricksBlock;
import net.chromatic.mod.block.BrownInvertedBrickStairsBlock;
import net.chromatic.mod.block.BrownInvertedBrickSlabBlock;
import net.chromatic.mod.block.BrownCutInvertedTileBlock;
import net.chromatic.mod.block.BrownCutInvertedStairsBlock;
import net.chromatic.mod.block.BrownCutInvertedSlabBlock;
import net.chromatic.mod.block.BrownCutChromaTileBlock;
import net.chromatic.mod.block.BrownCutChromaStairsBlock;
import net.chromatic.mod.block.BrownCutChromaSlabBlock;
import net.chromatic.mod.block.BrownChromaTileBlock;
import net.chromatic.mod.block.BrownChromaStairsBlock;
import net.chromatic.mod.block.BrownChromaSlabBlock;
import net.chromatic.mod.block.BrownChromaBricksBlock;
import net.chromatic.mod.block.BrownChromaBrickStairsBlock;
import net.chromatic.mod.block.BrownChromaBrickSlabBlock;
import net.chromatic.mod.block.BlueSmallInvertedBricksBlock;
import net.chromatic.mod.block.BlueSmallInvertedBrickStairsBlock;
import net.chromatic.mod.block.BlueSmallInvertedBrickSlabBlock;
import net.chromatic.mod.block.BlueSmallChromaBricksBlock;
import net.chromatic.mod.block.BlueSmallChromaBrickStairsBlock;
import net.chromatic.mod.block.BlueSmallChromaBrickSlabBlock;
import net.chromatic.mod.block.BlueInvertedTileBlock;
import net.chromatic.mod.block.BlueInvertedStairsBlock;
import net.chromatic.mod.block.BlueInvertedSlabBlock;
import net.chromatic.mod.block.BlueInvertedBricksBlock;
import net.chromatic.mod.block.BlueInvertedBrickStairsBlock;
import net.chromatic.mod.block.BlueInvertedBrickSlabBlock;
import net.chromatic.mod.block.BlueCutInvertedTileBlock;
import net.chromatic.mod.block.BlueCutInvertedStairsBlock;
import net.chromatic.mod.block.BlueCutInvertedSlabBlock;
import net.chromatic.mod.block.BlueCutChromaTileBlock;
import net.chromatic.mod.block.BlueCutChromaStairsBlock;
import net.chromatic.mod.block.BlueCutChromaSlabBlock;
import net.chromatic.mod.block.BlueChromaTileBlock;
import net.chromatic.mod.block.BlueChromaStairsBlock;
import net.chromatic.mod.block.BlueChromaSlabBlock;
import net.chromatic.mod.block.BlueChromaBricksBlock;
import net.chromatic.mod.block.BlueChromaBrickStairsBlock;
import net.chromatic.mod.block.BlueChromaBrickSlabBlock;
import net.chromatic.mod.ChromaticMod;

public class ChromaticModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ChromaticMod.MODID);
	public static final RegistryObject<Block> CHROMA_TILE = REGISTRY.register("chroma_tile", () -> new ChromaTileBlock());
	public static final RegistryObject<Block> BLUE_CHROMA_TILE = REGISTRY.register("blue_chroma_tile", () -> new BlueChromaTileBlock());
	public static final RegistryObject<Block> BROWN_CHROMA_TILE = REGISTRY.register("brown_chroma_tile", () -> new BrownChromaTileBlock());
	public static final RegistryObject<Block> CYAN_CHROMA_TILE = REGISTRY.register("cyan_chroma_tile", () -> new CyanChromaTileBlock());
	public static final RegistryObject<Block> GRAY_CHROMA_TILE = REGISTRY.register("gray_chroma_tile", () -> new GrayChromaTileBlock());
	public static final RegistryObject<Block> GREEN_CHROMA_TILE = REGISTRY.register("green_chroma_tile", () -> new GreenChromaTileBlock());
	public static final RegistryObject<Block> MAGENTA_CHROMA_TILE = REGISTRY.register("magenta_chroma_tile", () -> new MagentaChromaTileBlock());
	public static final RegistryObject<Block> ORANGE_CHROMA_TILE = REGISTRY.register("orange_chroma_tile", () -> new OrangeChromaTileBlock());
	public static final RegistryObject<Block> PINK_CHROMA_TILE = REGISTRY.register("pink_chroma_tile", () -> new PinkChromaTileBlock());
	public static final RegistryObject<Block> PURPLE_CHROMA_TILE = REGISTRY.register("purple_chroma_tile", () -> new PurpleChromaTileBlock());
	public static final RegistryObject<Block> RED_CHROMA_TILE = REGISTRY.register("red_chroma_tile", () -> new RedChromaTileBlock());
	public static final RegistryObject<Block> YELLOW_CHROMA_TILE = REGISTRY.register("yellow_chroma_tile", () -> new YellowChromaTileBlock());
	public static final RegistryObject<Block> INVERTED_TILE = REGISTRY.register("inverted_tile", () -> new InvertedTileBlock());
	public static final RegistryObject<Block> BLUE_INVERTED_TILE = REGISTRY.register("blue_inverted_tile", () -> new BlueInvertedTileBlock());
	public static final RegistryObject<Block> BROWN_INVERTED_TILE = REGISTRY.register("brown_inverted_tile", () -> new BrownInvertedTileBlock());
	public static final RegistryObject<Block> CYAN_INVERTED_TILE = REGISTRY.register("cyan_inverted_tile", () -> new CyanInvertedTileBlock());
	public static final RegistryObject<Block> GRAY_INVERTED_TILE = REGISTRY.register("gray_inverted_tile", () -> new GrayInvertedTileBlock());
	public static final RegistryObject<Block> GREEN_INVERTED_TILE = REGISTRY.register("green_inverted_tile", () -> new GreenInvertedTileBlock());
	public static final RegistryObject<Block> MAGENTA_INVERTED_TILE = REGISTRY.register("magenta_inverted_tile", () -> new MagentaInvertedTileBlock());
	public static final RegistryObject<Block> ORANGE_INVERTED_TILE = REGISTRY.register("orange_inverted_tile", () -> new OrangeInvertedTileBlock());
	public static final RegistryObject<Block> PINK_INVERTED_TILE = REGISTRY.register("pink_inverted_tile", () -> new PinkInvertedTileBlock());
	public static final RegistryObject<Block> PURPLE_INVERTED_TILE = REGISTRY.register("purple_inverted_tile", () -> new PurpleInvertedTileBlock());
	public static final RegistryObject<Block> RED_INVERTED_TILE = REGISTRY.register("red_inverted_tile", () -> new RedInvertedTileBlock());
	public static final RegistryObject<Block> YELLOW_INVERTED_TILE = REGISTRY.register("yellow_inverted_tile", () -> new YellowInvertedTileBlock());
	public static final RegistryObject<Block> CUT_CHROMA_TILE = REGISTRY.register("cut_chroma_tile", () -> new CutChromaTileBlock());
	public static final RegistryObject<Block> BLUE_CUT_CHROMA_TILE = REGISTRY.register("blue_cut_chroma_tile", () -> new BlueCutChromaTileBlock());
	public static final RegistryObject<Block> BROWN_CUT_CHROMA_TILE = REGISTRY.register("brown_cut_chroma_tile", () -> new BrownCutChromaTileBlock());
	public static final RegistryObject<Block> CYAN_CUT_CHROMA_TILE = REGISTRY.register("cyan_cut_chroma_tile", () -> new CyanCutChromaTileBlock());
	public static final RegistryObject<Block> GRAY_CUT_CHROMA_TILE = REGISTRY.register("gray_cut_chroma_tile", () -> new GrayCutChromaTileBlock());
	public static final RegistryObject<Block> GREEN_CUT_CHROMA_TILE = REGISTRY.register("green_cut_chroma_tile", () -> new GreenCutChromaTileBlock());
	public static final RegistryObject<Block> MAGENTA_CUT_CHROMA_TILE = REGISTRY.register("magenta_cut_chroma_tile", () -> new MagentaCutChromaTileBlock());
	public static final RegistryObject<Block> ORANGE_CUT_CHROMA_TILE = REGISTRY.register("orange_cut_chroma_tile", () -> new OrangeCutChromaTileBlock());
	public static final RegistryObject<Block> PINK_CUT_CHROMA_TILE = REGISTRY.register("pink_cut_chroma_tile", () -> new PinkCutChromaTileBlock());
	public static final RegistryObject<Block> PURPLE_CUT_CHROMA_TILE = REGISTRY.register("purple_cut_chroma_tile", () -> new PurpleCutChromaTileBlock());
	public static final RegistryObject<Block> RED_CUT_CHROMA_TILE = REGISTRY.register("red_cut_chroma_tile", () -> new RedCutChromaTileBlock());
	public static final RegistryObject<Block> YELLOW_CUT_CHROMA_TILE = REGISTRY.register("yellow_cut_chroma_tile", () -> new YellowCutChromaTileBlock());
	public static final RegistryObject<Block> CUT_INVERTED_TILE = REGISTRY.register("cut_inverted_tile", () -> new CutInvertedTileBlock());
	public static final RegistryObject<Block> BLUE_CUT_INVERTED_TILE = REGISTRY.register("blue_cut_inverted_tile", () -> new BlueCutInvertedTileBlock());
	public static final RegistryObject<Block> BROWN_CUT_INVERTED_TILE = REGISTRY.register("brown_cut_inverted_tile", () -> new BrownCutInvertedTileBlock());
	public static final RegistryObject<Block> CYAN_CUT_INVERTED_TILE = REGISTRY.register("cyan_cut_inverted_tile", () -> new CyanCutInvertedTileBlock());
	public static final RegistryObject<Block> GRAY_CUT_INVERTED_TILE = REGISTRY.register("gray_cut_inverted_tile", () -> new GrayCutInvertedTileBlock());
	public static final RegistryObject<Block> GREEN_CUT_INVERTED_TILE = REGISTRY.register("green_cut_inverted_tile", () -> new GreenCutInvertedTileBlock());
	public static final RegistryObject<Block> MAGENTE_CUT_INVERTED_TILE = REGISTRY.register("magente_cut_inverted_tile", () -> new MagenteCutInvertedTileBlock());
	public static final RegistryObject<Block> ORANGE_CUT_INVERTED_TILE = REGISTRY.register("orange_cut_inverted_tile", () -> new OrangeCutInvertedTileBlock());
	public static final RegistryObject<Block> PINK_CUT_INVERTED_TILE = REGISTRY.register("pink_cut_inverted_tile", () -> new PinkCutInvertedTileBlock());
	public static final RegistryObject<Block> PURPLE_CUT_INVERTED_TILE = REGISTRY.register("purple_cut_inverted_tile", () -> new PurpleCutInvertedTileBlock());
	public static final RegistryObject<Block> RED_CUT_INVERTED_TILE = REGISTRY.register("red_cut_inverted_tile", () -> new RedCutInvertedTileBlock());
	public static final RegistryObject<Block> YELLOW_CUT_INVERTED_TILE = REGISTRY.register("yellow_cut_inverted_tile", () -> new YellowCutInvertedTileBlock());
	public static final RegistryObject<Block> CHROMA_BRICKS = REGISTRY.register("chroma_bricks", () -> new ChromaBricksBlock());
	public static final RegistryObject<Block> BLUE_CHROMA_BRICKS = REGISTRY.register("blue_chroma_bricks", () -> new BlueChromaBricksBlock());
	public static final RegistryObject<Block> BROWN_CHROMA_BRICKS = REGISTRY.register("brown_chroma_bricks", () -> new BrownChromaBricksBlock());
	public static final RegistryObject<Block> CYAN_CHROMA_BRICKS = REGISTRY.register("cyan_chroma_bricks", () -> new CyanChromaBricksBlock());
	public static final RegistryObject<Block> GRAY_CHROMA_BRICKS = REGISTRY.register("gray_chroma_bricks", () -> new GrayChromaBricksBlock());
	public static final RegistryObject<Block> GREEN_CHROMA_BRICKS = REGISTRY.register("green_chroma_bricks", () -> new GreenChromaBricksBlock());
	public static final RegistryObject<Block> MAGENTA_CHROMA_BRICKS = REGISTRY.register("magenta_chroma_bricks", () -> new MagentaChromaBricksBlock());
	public static final RegistryObject<Block> ORANGE_CHROMA_BRICKS = REGISTRY.register("orange_chroma_bricks", () -> new OrangeChromaBricksBlock());
	public static final RegistryObject<Block> PINK_CHROMA_BRICKS = REGISTRY.register("pink_chroma_bricks", () -> new PinkChromaBricksBlock());
	public static final RegistryObject<Block> PURPLE_CHROMA_BRICKS = REGISTRY.register("purple_chroma_bricks", () -> new PurpleChromaBricksBlock());
	public static final RegistryObject<Block> RED_CHROMA_BRICKS = REGISTRY.register("red_chroma_bricks", () -> new RedChromaBricksBlock());
	public static final RegistryObject<Block> YELLOW_CHROMA_BRICKS = REGISTRY.register("yellow_chroma_bricks", () -> new YellowChromaBricksBlock());
	public static final RegistryObject<Block> INVERTED_BRICKS = REGISTRY.register("inverted_bricks", () -> new InvertedBricksBlock());
	public static final RegistryObject<Block> BLUE_INVERTED_BRICKS = REGISTRY.register("blue_inverted_bricks", () -> new BlueInvertedBricksBlock());
	public static final RegistryObject<Block> BROWN_INVERTED_BRICKS = REGISTRY.register("brown_inverted_bricks", () -> new BrownInvertedBricksBlock());
	public static final RegistryObject<Block> CYAN_INVERTED_BRICKS = REGISTRY.register("cyan_inverted_bricks", () -> new CyanInvertedBricksBlock());
	public static final RegistryObject<Block> GRAY_INVERTED_BRICKS = REGISTRY.register("gray_inverted_bricks", () -> new GrayInvertedBricksBlock());
	public static final RegistryObject<Block> GREEN_INVERTED_BRICKS = REGISTRY.register("green_inverted_bricks", () -> new GreenInvertedBricksBlock());
	public static final RegistryObject<Block> MAGENTA_INVERTED_BRICKS = REGISTRY.register("magenta_inverted_bricks", () -> new MagentaInvertedBricksBlock());
	public static final RegistryObject<Block> ORANGE_INVERTED_BRICKS = REGISTRY.register("orange_inverted_bricks", () -> new OrangeInvertedBricksBlock());
	public static final RegistryObject<Block> PINK_INVERTED_BRICKS = REGISTRY.register("pink_inverted_bricks", () -> new PinkInvertedBricksBlock());
	public static final RegistryObject<Block> PURPLE_INVERTED_BRICKS = REGISTRY.register("purple_inverted_bricks", () -> new PurpleInvertedBricksBlock());
	public static final RegistryObject<Block> RED_INVERTED_BRICKS = REGISTRY.register("red_inverted_bricks", () -> new RedInvertedBricksBlock());
	public static final RegistryObject<Block> YELLOW_INVERTED_BRICKS = REGISTRY.register("yellow_inverted_bricks", () -> new YellowInvertedBricksBlock());
	public static final RegistryObject<Block> SMALL_CHROMA_BRICKS = REGISTRY.register("small_chroma_bricks", () -> new SmallChromaBricksBlock());
	public static final RegistryObject<Block> BLUE_SMALL_CHROMA_BRICKS = REGISTRY.register("blue_small_chroma_bricks", () -> new BlueSmallChromaBricksBlock());
	public static final RegistryObject<Block> BROWN_SMALL_CHROMA_BRICKS = REGISTRY.register("brown_small_chroma_bricks", () -> new BrownSmallChromaBricksBlock());
	public static final RegistryObject<Block> CYAN_SMALL_CHROMA_BRICKS = REGISTRY.register("cyan_small_chroma_bricks", () -> new CyanSmallChromaBricksBlock());
	public static final RegistryObject<Block> GRAY_SMALL_CHROMA_BRICKS = REGISTRY.register("gray_small_chroma_bricks", () -> new GraySmallChromaBricksBlock());
	public static final RegistryObject<Block> GREEN_SMALL_CHROMA_BRICKS = REGISTRY.register("green_small_chroma_bricks", () -> new GreenSmallChromaBricksBlock());
	public static final RegistryObject<Block> MAGENTA_SMALL_CHROMA_BRICKS = REGISTRY.register("magenta_small_chroma_bricks", () -> new MagentaSmallChromaBricksBlock());
	public static final RegistryObject<Block> ORANGE_SMALL_CHROMA_BRICKS = REGISTRY.register("orange_small_chroma_bricks", () -> new OrangeSmallChromaBricksBlock());
	public static final RegistryObject<Block> PINK_SMALL_CHROMA_BRICKS = REGISTRY.register("pink_small_chroma_bricks", () -> new PinkSmallChromaBricksBlock());
	public static final RegistryObject<Block> PURPLE_SMALL_CHROMA_BRICKS = REGISTRY.register("purple_small_chroma_bricks", () -> new PurpleSmallChromaBricksBlock());
	public static final RegistryObject<Block> RED_SMALL_CHROMA_BRICKS = REGISTRY.register("red_small_chroma_bricks", () -> new RedSmallChromaBricksBlock());
	public static final RegistryObject<Block> YELLOW_SMALL_CHROMA_BRICKS = REGISTRY.register("yellow_small_chroma_bricks", () -> new YellowSmallChromaBricksBlock());
	public static final RegistryObject<Block> SMALL_INVERTED_BRICKS = REGISTRY.register("small_inverted_bricks", () -> new SmallInvertedBricksBlock());
	public static final RegistryObject<Block> BLUE_SMALL_INVERTED_BRICKS = REGISTRY.register("blue_small_inverted_bricks", () -> new BlueSmallInvertedBricksBlock());
	public static final RegistryObject<Block> BROWN_SMALL_INVERTED_BRICKS = REGISTRY.register("brown_small_inverted_bricks", () -> new BrownSmallInvertedBricksBlock());
	public static final RegistryObject<Block> CYAN_SMALL_INVERTED_BRICKS = REGISTRY.register("cyan_small_inverted_bricks", () -> new CyanSmallInvertedBricksBlock());
	public static final RegistryObject<Block> GRAY_SMALL_INVERTED_BRICKS = REGISTRY.register("gray_small_inverted_bricks", () -> new GraySmallInvertedBricksBlock());
	public static final RegistryObject<Block> GREEN_SMALL_INVERTED_BRICKS = REGISTRY.register("green_small_inverted_bricks", () -> new GreenSmallInvertedBricksBlock());
	public static final RegistryObject<Block> MAGENTA_SMALL_INVERTED_BRICKS = REGISTRY.register("magenta_small_inverted_bricks", () -> new MagentaSmallInvertedBricksBlock());
	public static final RegistryObject<Block> ORANGE_SMALL_INVERTED_BRICKS = REGISTRY.register("orange_small_inverted_bricks", () -> new OrangeSmallInvertedBricksBlock());
	public static final RegistryObject<Block> PINK_SMALL_INVERTED_BRICKS = REGISTRY.register("pink_small_inverted_bricks", () -> new PinkSmallInvertedBricksBlock());
	public static final RegistryObject<Block> PURPLE_SMALL_INVERTED_BRICKS = REGISTRY.register("purple_small_inverted_bricks", () -> new PurpleSmallInvertedBricksBlock());
	public static final RegistryObject<Block> RED_SMALL_INVERTED_BRICKS = REGISTRY.register("red_small_inverted_bricks", () -> new RedSmallInvertedBricksBlock());
	public static final RegistryObject<Block> YELLOW_SMALL_INVERTED_BRICKS = REGISTRY.register("yellow_small_inverted_bricks", () -> new YellowSmallInvertedBricksBlock());
	public static final RegistryObject<Block> CHROMA_SLAB = REGISTRY.register("chroma_slab", () -> new ChromaSlabBlock());
	public static final RegistryObject<Block> BLUE_CHROMA_SLAB = REGISTRY.register("blue_chroma_slab", () -> new BlueChromaSlabBlock());
	public static final RegistryObject<Block> BROWN_CHROMA_SLAB = REGISTRY.register("brown_chroma_slab", () -> new BrownChromaSlabBlock());
	public static final RegistryObject<Block> CYAN_CHROMA_SLAB = REGISTRY.register("cyan_chroma_slab", () -> new CyanChromaSlabBlock());
	public static final RegistryObject<Block> GRAY_CHROMA_SLAB = REGISTRY.register("gray_chroma_slab", () -> new GrayChromaSlabBlock());
	public static final RegistryObject<Block> GREEN_CHROMA_SLAB = REGISTRY.register("green_chroma_slab", () -> new GreenChromaSlabBlock());
	public static final RegistryObject<Block> MAGENTA_CHROMA_SLAB = REGISTRY.register("magenta_chroma_slab", () -> new MagentaChromaSlabBlock());
	public static final RegistryObject<Block> ORANGE_CHROMA_SLAB = REGISTRY.register("orange_chroma_slab", () -> new OrangeChromaSlabBlock());
	public static final RegistryObject<Block> PINK_CHROMA_SLAB = REGISTRY.register("pink_chroma_slab", () -> new PinkChromaSlabBlock());
	public static final RegistryObject<Block> PURPLE_CHROMA_SLAB = REGISTRY.register("purple_chroma_slab", () -> new PurpleChromaSlabBlock());
	public static final RegistryObject<Block> RED_CHROMA_SLAB = REGISTRY.register("red_chroma_slab", () -> new RedChromaSlabBlock());
	public static final RegistryObject<Block> YELLOW_CHROMA_SLAB = REGISTRY.register("yellow_chroma_slab", () -> new YellowChromaSlabBlock());
	public static final RegistryObject<Block> INVERTED_SLAB = REGISTRY.register("inverted_slab", () -> new InvertedSlabBlock());
	public static final RegistryObject<Block> BLUE_INVERTED_SLAB = REGISTRY.register("blue_inverted_slab", () -> new BlueInvertedSlabBlock());
	public static final RegistryObject<Block> BROWN_INVERTED_SLAB = REGISTRY.register("brown_inverted_slab", () -> new BrownInvertedSlabBlock());
	public static final RegistryObject<Block> CYAN_INVERTED_SLAB = REGISTRY.register("cyan_inverted_slab", () -> new CyanInvertedSlabBlock());
	public static final RegistryObject<Block> GRAY_INVERTED_SLAB = REGISTRY.register("gray_inverted_slab", () -> new GrayInvertedSlabBlock());
	public static final RegistryObject<Block> GREEN_INVERTED_SLAB = REGISTRY.register("green_inverted_slab", () -> new GreenInvertedSlabBlock());
	public static final RegistryObject<Block> MAGENTA_INVERTED_SLAB = REGISTRY.register("magenta_inverted_slab", () -> new MagentaInvertedSlabBlock());
	public static final RegistryObject<Block> ORANGE_INVERTED_SLAB = REGISTRY.register("orange_inverted_slab", () -> new OrangeInvertedSlabBlock());
	public static final RegistryObject<Block> PINK_INVERTED_SLAB = REGISTRY.register("pink_inverted_slab", () -> new PinkInvertedSlabBlock());
	public static final RegistryObject<Block> PURPLE_INVERTED_SLAB = REGISTRY.register("purple_inverted_slab", () -> new PurpleInvertedSlabBlock());
	public static final RegistryObject<Block> RED_INVERTED_SLAB = REGISTRY.register("red_inverted_slab", () -> new RedInvertedSlabBlock());
	public static final RegistryObject<Block> YELLOW_INVERTED_SLAB = REGISTRY.register("yellow_inverted_slab", () -> new YellowInvertedSlabBlock());
	public static final RegistryObject<Block> CYAN_CUT_INVERTED_SLAB = REGISTRY.register("cyan_cut_inverted_slab", () -> new CyanCutInvertedSlabBlock());
	public static final RegistryObject<Block> CUT_CHROMA_SLAB = REGISTRY.register("cut_chroma_slab", () -> new CutChromaSlabBlock());
	public static final RegistryObject<Block> BLUE_CUT_CHROMA_SLAB = REGISTRY.register("blue_cut_chroma_slab", () -> new BlueCutChromaSlabBlock());
	public static final RegistryObject<Block> BROWN_CUT_CHROMA_SLAB = REGISTRY.register("brown_cut_chroma_slab", () -> new BrownCutChromaSlabBlock());
	public static final RegistryObject<Block> CYAN_CUT_CHROMA_SLAB = REGISTRY.register("cyan_cut_chroma_slab", () -> new CyanCutChromaSlabBlock());
	public static final RegistryObject<Block> GRAY_CUT_CHROMA_SLAB = REGISTRY.register("gray_cut_chroma_slab", () -> new GrayCutChromaSlabBlock());
	public static final RegistryObject<Block> GREEN_CUT_CHROMA_SLAB = REGISTRY.register("green_cut_chroma_slab", () -> new GreenCutChromaSlabBlock());
	public static final RegistryObject<Block> MAGENTA_CUT_CHROMA_SLAB = REGISTRY.register("magenta_cut_chroma_slab", () -> new MagentaCutChromaSlabBlock());
	public static final RegistryObject<Block> ORANGE_CUT_CHROMA_SLAB = REGISTRY.register("orange_cut_chroma_slab", () -> new OrangeCutChromaSlabBlock());
	public static final RegistryObject<Block> PINK_CUT_CHROMA_SLAB = REGISTRY.register("pink_cut_chroma_slab", () -> new PinkCutChromaSlabBlock());
	public static final RegistryObject<Block> PURPLE_CUT_CHROMA_SLAB = REGISTRY.register("purple_cut_chroma_slab", () -> new PurpleCutChromaSlabBlock());
	public static final RegistryObject<Block> RED_CUT_CHROMA_SLAB = REGISTRY.register("red_cut_chroma_slab", () -> new RedCutChromaSlabBlock());
	public static final RegistryObject<Block> YELLOW_CUT_CHROMA_SLAB = REGISTRY.register("yellow_cut_chroma_slab", () -> new YellowCutChromaSlabBlock());
	public static final RegistryObject<Block> BLUE_CUT_INVERTED_SLAB = REGISTRY.register("blue_cut_inverted_slab", () -> new BlueCutInvertedSlabBlock());
	public static final RegistryObject<Block> BROWN_CUT_INVERTED_SLAB = REGISTRY.register("brown_cut_inverted_slab", () -> new BrownCutInvertedSlabBlock());
	public static final RegistryObject<Block> CUT_INVERTED_SLAB = REGISTRY.register("cut_inverted_slab", () -> new CutInvertedSlabBlock());
	public static final RegistryObject<Block> GRAY_CUT_INVERTED_SLAB = REGISTRY.register("gray_cut_inverted_slab", () -> new GrayCutInvertedSlabBlock());
	public static final RegistryObject<Block> GREEN_CUT_INVERTED_SLAB = REGISTRY.register("green_cut_inverted_slab", () -> new GreenCutInvertedSlabBlock());
	public static final RegistryObject<Block> MAGENTA_CUT_INVERTED_SLAB = REGISTRY.register("magenta_cut_inverted_slab", () -> new MagentaCutInvertedSlabBlock());
	public static final RegistryObject<Block> ORANGE_CUT_INVERTED_SLAB = REGISTRY.register("orange_cut_inverted_slab", () -> new OrangeCutInvertedSlabBlock());
	public static final RegistryObject<Block> PINK_CUT_INVERTED_SLAB = REGISTRY.register("pink_cut_inverted_slab", () -> new PinkCutInvertedSlabBlock());
	public static final RegistryObject<Block> PURPLE_CUT_INVERTED_SLAB = REGISTRY.register("purple_cut_inverted_slab", () -> new PurpleCutInvertedSlabBlock());
	public static final RegistryObject<Block> RED_CUT_INVERTED_SLAB = REGISTRY.register("red_cut_inverted_slab", () -> new RedCutInvertedSlabBlock());
	public static final RegistryObject<Block> YELLOW_CUT_INVERTED_SLAB = REGISTRY.register("yellow_cut_inverted_slab", () -> new YellowCutInvertedSlabBlock());
	public static final RegistryObject<Block> CHROMA_BRICK_SLAB = REGISTRY.register("chroma_brick_slab", () -> new ChromaBrickSlabBlock());
	public static final RegistryObject<Block> BLUE_CHROMA_BRICK_SLAB = REGISTRY.register("blue_chroma_brick_slab", () -> new BlueChromaBrickSlabBlock());
	public static final RegistryObject<Block> BROWN_CHROMA_BRICK_SLAB = REGISTRY.register("brown_chroma_brick_slab", () -> new BrownChromaBrickSlabBlock());
	public static final RegistryObject<Block> CYAN_CHROMA_BRICK_SLAB = REGISTRY.register("cyan_chroma_brick_slab", () -> new CyanChromaBrickSlabBlock());
	public static final RegistryObject<Block> GRAY_CHROMA_BRICK_SLAB = REGISTRY.register("gray_chroma_brick_slab", () -> new GrayChromaBrickSlabBlock());
	public static final RegistryObject<Block> GREEN_CHROMA_BRICK_SLAB = REGISTRY.register("green_chroma_brick_slab", () -> new GreenChromaBrickSlabBlock());
	public static final RegistryObject<Block> MAGENTA_CHROMA_BRICK_SLAB = REGISTRY.register("magenta_chroma_brick_slab", () -> new MagentaChromaBrickSlabBlock());
	public static final RegistryObject<Block> ORANGE_CHROMA_BRICK_SLAB = REGISTRY.register("orange_chroma_brick_slab", () -> new OrangeChromaBrickSlabBlock());
	public static final RegistryObject<Block> PINK_CHROMA_BRICK_SLAB = REGISTRY.register("pink_chroma_brick_slab", () -> new PinkChromaBrickSlabBlock());
	public static final RegistryObject<Block> PURPLE_CHROMA_BRICK_SLAB = REGISTRY.register("purple_chroma_brick_slab", () -> new PurpleChromaBrickSlabBlock());
	public static final RegistryObject<Block> RED_CHROMA_BRICK_SLAB = REGISTRY.register("red_chroma_brick_slab", () -> new RedChromaBrickSlabBlock());
	public static final RegistryObject<Block> YELLOW_CHROMA_BRICK_SLAB = REGISTRY.register("yellow_chroma_brick_slab", () -> new YellowChromaBrickSlabBlock());
	public static final RegistryObject<Block> INVERTED_BRICK_SLAB = REGISTRY.register("inverted_brick_slab", () -> new InvertedBrickSlabBlock());
	public static final RegistryObject<Block> BLUE_INVERTED_BRICK_SLAB = REGISTRY.register("blue_inverted_brick_slab", () -> new BlueInvertedBrickSlabBlock());
	public static final RegistryObject<Block> BROWN_INVERTED_BRICK_SLAB = REGISTRY.register("brown_inverted_brick_slab", () -> new BrownInvertedBrickSlabBlock());
	public static final RegistryObject<Block> CYAN_INVERTED_BRICK_SLAB = REGISTRY.register("cyan_inverted_brick_slab", () -> new CyanInvertedBrickSlabBlock());
	public static final RegistryObject<Block> GRAY_INVERTED_BRICK_SLAB = REGISTRY.register("gray_inverted_brick_slab", () -> new GrayInvertedBrickSlabBlock());
	public static final RegistryObject<Block> GREEN_INVERTED_BRICK_SLAB = REGISTRY.register("green_inverted_brick_slab", () -> new GreenInvertedBrickSlabBlock());
	public static final RegistryObject<Block> MAGENTA_INVERTED_BRICK_SLAB = REGISTRY.register("magenta_inverted_brick_slab", () -> new MagentaInvertedBrickSlabBlock());
	public static final RegistryObject<Block> ORANGE_INVERTED_BRICK_SLAB = REGISTRY.register("orange_inverted_brick_slab", () -> new OrangeInvertedBrickSlabBlock());
	public static final RegistryObject<Block> PINK_INVERTED_BRICK_SLAB = REGISTRY.register("pink_inverted_brick_slab", () -> new PinkInvertedBrickSlabBlock());
	public static final RegistryObject<Block> PURPLE_INVERTED_BRICK_SLAB = REGISTRY.register("purple_inverted_brick_slab", () -> new PurpleInvertedBrickSlabBlock());
	public static final RegistryObject<Block> RED_INVERTED_BRICK_SLAB = REGISTRY.register("red_inverted_brick_slab", () -> new RedInvertedBrickSlabBlock());
	public static final RegistryObject<Block> YELLOW_INVERTED_BRICK_SLAB = REGISTRY.register("yellow_inverted_brick_slab", () -> new YellowInvertedBrickSlabBlock());
	public static final RegistryObject<Block> SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("small_chroma_brick_slab", () -> new SmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> BLUE_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("blue_small_chroma_brick_slab", () -> new BlueSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> BROWN_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("brown_small_chroma_brick_slab", () -> new BrownSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> CYAN_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("cyan_small_chroma_brick_slab", () -> new CyanSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> GRAY_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("gray_small_chroma_brick_slab", () -> new GraySmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> GREEN_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("green_small_chroma_brick_slab", () -> new GreenSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> MAGENTA_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("magenta_small_chroma_brick_slab", () -> new MagentaSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> ORANGE_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("orange_small_chroma_brick_slab", () -> new OrangeSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> PINK_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("pink_small_chroma_brick_slab", () -> new PinkSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> PURPLE_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("purple_small_chroma_brick_slab", () -> new PurpleSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> RED_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("red_small_chroma_brick_slab", () -> new RedSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> YELLOW_SMALL_CHROMA_BRICK_SLAB = REGISTRY.register("yellow_small_chroma_brick_slab", () -> new YellowSmallChromaBrickSlabBlock());
	public static final RegistryObject<Block> SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("small_inverted_brick_slab", () -> new SmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> BLUE_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("blue_small_inverted_brick_slab", () -> new BlueSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> BROWN_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("brown_small_inverted_brick_slab", () -> new BrownSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> CYAN_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("cyan_small_inverted_brick_slab", () -> new CyanSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> GRAY_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("gray_small_inverted_brick_slab", () -> new GraySmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> GREEN_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("green_small_inverted_brick_slab", () -> new GreenSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> MAGENTA_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("magenta_small_inverted_brick_slab", () -> new MagentaSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> ORANGE_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("orange_small_inverted_brick_slab", () -> new OrangeSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> PINK_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("pink_small_inverted_brick_slab", () -> new PinkSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> PURPLE_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("purple_small_inverted_brick_slab", () -> new PurpleSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> RED_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("red_small_inverted_brick_slab", () -> new RedSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> YELLOW_SMALL_INVERTED_BRICK_SLAB = REGISTRY.register("yellow_small_inverted_brick_slab", () -> new YellowSmallInvertedBrickSlabBlock());
	public static final RegistryObject<Block> CHROMA_STAIRS = REGISTRY.register("chroma_stairs", () -> new ChromaStairsBlock());
	public static final RegistryObject<Block> BLUE_CHROMA_STAIRS = REGISTRY.register("blue_chroma_stairs", () -> new BlueChromaStairsBlock());
	public static final RegistryObject<Block> BROWN_CHROMA_STAIRS = REGISTRY.register("brown_chroma_stairs", () -> new BrownChromaStairsBlock());
	public static final RegistryObject<Block> CYAN_CHROMA_STAIRS = REGISTRY.register("cyan_chroma_stairs", () -> new CyanChromaStairsBlock());
	public static final RegistryObject<Block> GRAY_CHROMA_STAIRS = REGISTRY.register("gray_chroma_stairs", () -> new GrayChromaStairsBlock());
	public static final RegistryObject<Block> GREEN_CHROMA_STAIRS = REGISTRY.register("green_chroma_stairs", () -> new GreenChromaStairsBlock());
	public static final RegistryObject<Block> MAGENTA_CHROMA_STAIRS = REGISTRY.register("magenta_chroma_stairs", () -> new MagentaChromaStairsBlock());
	public static final RegistryObject<Block> ORANGE_CHROMA_STAIRS = REGISTRY.register("orange_chroma_stairs", () -> new OrangeChromaStairsBlock());
	public static final RegistryObject<Block> PINK_CHROMA_STAIRS = REGISTRY.register("pink_chroma_stairs", () -> new PinkChromaStairsBlock());
	public static final RegistryObject<Block> PURPLE_CHROMA_STAIRS = REGISTRY.register("purple_chroma_stairs", () -> new PurpleChromaStairsBlock());
	public static final RegistryObject<Block> RED_CHROMA_STAIRS = REGISTRY.register("red_chroma_stairs", () -> new RedChromaStairsBlock());
	public static final RegistryObject<Block> YELLOW_CHROMA_STAIRS = REGISTRY.register("yellow_chroma_stairs", () -> new YellowChromaStairsBlock());
	public static final RegistryObject<Block> INVERTED_STAIRS = REGISTRY.register("inverted_stairs", () -> new InvertedStairsBlock());
	public static final RegistryObject<Block> BLUE_INVERTED_STAIRS = REGISTRY.register("blue_inverted_stairs", () -> new BlueInvertedStairsBlock());
	public static final RegistryObject<Block> BROWN_INVERTED_STAIRS = REGISTRY.register("brown_inverted_stairs", () -> new BrownInvertedStairsBlock());
	public static final RegistryObject<Block> CYAN_INVERTED_STAIRS = REGISTRY.register("cyan_inverted_stairs", () -> new CyanInvertedStairsBlock());
	public static final RegistryObject<Block> GRAY_INVERTED_STAIRS = REGISTRY.register("gray_inverted_stairs", () -> new GrayInvertedStairsBlock());
	public static final RegistryObject<Block> GREEN_INVERTED_STAIRS = REGISTRY.register("green_inverted_stairs", () -> new GreenInvertedStairsBlock());
	public static final RegistryObject<Block> MAGENTA_INVERTED_STAIRS = REGISTRY.register("magenta_inverted_stairs", () -> new MagentaInvertedStairsBlock());
	public static final RegistryObject<Block> ORANGE_INVERTED_STAIRS = REGISTRY.register("orange_inverted_stairs", () -> new OrangeInvertedStairsBlock());
	public static final RegistryObject<Block> PINK_INVERTED_STAIRS = REGISTRY.register("pink_inverted_stairs", () -> new PinkInvertedStairsBlock());
	public static final RegistryObject<Block> PURPLE_INVERTED_STAIRS = REGISTRY.register("purple_inverted_stairs", () -> new PurpleInvertedStairsBlock());
	public static final RegistryObject<Block> RED_INVERTED_STAIRS = REGISTRY.register("red_inverted_stairs", () -> new RedInvertedStairsBlock());
	public static final RegistryObject<Block> YELLOW_INVERTED_STAIRS = REGISTRY.register("yellow_inverted_stairs", () -> new YellowInvertedStairsBlock());
	public static final RegistryObject<Block> CUT_CHROMA_STAIRS = REGISTRY.register("cut_chroma_stairs", () -> new CutChromaStairsBlock());
	public static final RegistryObject<Block> BLUE_CUT_CHROMA_STAIRS = REGISTRY.register("blue_cut_chroma_stairs", () -> new BlueCutChromaStairsBlock());
	public static final RegistryObject<Block> BROWN_CUT_CHROMA_STAIRS = REGISTRY.register("brown_cut_chroma_stairs", () -> new BrownCutChromaStairsBlock());
	public static final RegistryObject<Block> CYAN_CUT_CHROMA_STAIRS = REGISTRY.register("cyan_cut_chroma_stairs", () -> new CyanCutChromaStairsBlock());
	public static final RegistryObject<Block> GRAY_CUT_CHROMA_STAIRS = REGISTRY.register("gray_cut_chroma_stairs", () -> new GrayCutChromaStairsBlock());
	public static final RegistryObject<Block> GREEN_CUT_CHROMA_STAIRS = REGISTRY.register("green_cut_chroma_stairs", () -> new GreenCutChromaStairsBlock());
	public static final RegistryObject<Block> MAGENTA_CUT_CHROMA_STAIRS = REGISTRY.register("magenta_cut_chroma_stairs", () -> new MagentaCutChromaStairsBlock());
	public static final RegistryObject<Block> ORANGE_CUT_CHROMA_STAIRS = REGISTRY.register("orange_cut_chroma_stairs", () -> new OrangeCutChromaStairsBlock());
	public static final RegistryObject<Block> PINK_CUT_CHROMA_STAIRS = REGISTRY.register("pink_cut_chroma_stairs", () -> new PinkCutChromaStairsBlock());
	public static final RegistryObject<Block> PURPLE_CUT_CHROMA_STAIRS = REGISTRY.register("purple_cut_chroma_stairs", () -> new PurpleCutChromaStairsBlock());
	public static final RegistryObject<Block> RED_CUT_CHROMA_STAIRS = REGISTRY.register("red_cut_chroma_stairs", () -> new RedCutChromaStairsBlock());
	public static final RegistryObject<Block> YELLOW_CUT_CHROMA_STAIRS = REGISTRY.register("yellow_cut_chroma_stairs", () -> new YellowCutChromaStairsBlock());
	public static final RegistryObject<Block> CUT_INVERTED_STAIRS = REGISTRY.register("cut_inverted_stairs", () -> new CutInvertedStairsBlock());
	public static final RegistryObject<Block> BLUE_CUT_INVERTED_STAIRS = REGISTRY.register("blue_cut_inverted_stairs", () -> new BlueCutInvertedStairsBlock());
	public static final RegistryObject<Block> BROWN_CUT_INVERTED_STAIRS = REGISTRY.register("brown_cut_inverted_stairs", () -> new BrownCutInvertedStairsBlock());
	public static final RegistryObject<Block> CYAN_CUT_INVERTED_STAIRS = REGISTRY.register("cyan_cut_inverted_stairs", () -> new CyanCutInvertedStairsBlock());
	public static final RegistryObject<Block> GRAY_CUT_INVERTED_STAIRS = REGISTRY.register("gray_cut_inverted_stairs", () -> new GrayCutInvertedStairsBlock());
	public static final RegistryObject<Block> GREEN_CUT_INVERTED_STAIRS = REGISTRY.register("green_cut_inverted_stairs", () -> new GreenCutInvertedStairsBlock());
	public static final RegistryObject<Block> MAGENTA_CUT_INVERTED_STAIRS = REGISTRY.register("magenta_cut_inverted_stairs", () -> new MagentaCutInvertedStairsBlock());
	public static final RegistryObject<Block> ORANGE_CUT_INVERTED_STAIRS = REGISTRY.register("orange_cut_inverted_stairs", () -> new OrangeCutInvertedStairsBlock());
	public static final RegistryObject<Block> PINK_CUT_INVERTED_STAIRS = REGISTRY.register("pink_cut_inverted_stairs", () -> new PinkCutInvertedStairsBlock());
	public static final RegistryObject<Block> PURPLE_CUT_INVERTED_STAIRS = REGISTRY.register("purple_cut_inverted_stairs", () -> new PurpleCutInvertedStairsBlock());
	public static final RegistryObject<Block> RED_CUT_INVERTED_STAIRS = REGISTRY.register("red_cut_inverted_stairs", () -> new RedCutInvertedStairsBlock());
	public static final RegistryObject<Block> YELLOW_CUT_INVERTED_STAIRS = REGISTRY.register("yellow_cut_inverted_stairs", () -> new YellowCutInvertedStairsBlock());
	public static final RegistryObject<Block> CHROMA_BRICK_STAIRS = REGISTRY.register("chroma_brick_stairs", () -> new ChromaBrickStairsBlock());
	public static final RegistryObject<Block> BLUE_CHROMA_BRICK_STAIRS = REGISTRY.register("blue_chroma_brick_stairs", () -> new BlueChromaBrickStairsBlock());
	public static final RegistryObject<Block> BROWN_CHROMA_BRICK_STAIRS = REGISTRY.register("brown_chroma_brick_stairs", () -> new BrownChromaBrickStairsBlock());
	public static final RegistryObject<Block> CYAN_CHROMA_BRICK_STAIRS = REGISTRY.register("cyan_chroma_brick_stairs", () -> new CyanChromaBrickStairsBlock());
	public static final RegistryObject<Block> GRAY_CHROMA_BRICK_STAIRS = REGISTRY.register("gray_chroma_brick_stairs", () -> new GrayChromaBrickStairsBlock());
	public static final RegistryObject<Block> GREEN_CHROMA_BRICK_STAIRS = REGISTRY.register("green_chroma_brick_stairs", () -> new GreenChromaBrickStairsBlock());
	public static final RegistryObject<Block> MAGENTA_CHROMA_BRICK_STAIRS = REGISTRY.register("magenta_chroma_brick_stairs", () -> new MagentaChromaBrickStairsBlock());
	public static final RegistryObject<Block> ORANGE_CHROMA_BRICK_STAIRS = REGISTRY.register("orange_chroma_brick_stairs", () -> new OrangeChromaBrickStairsBlock());
	public static final RegistryObject<Block> PINK_CHROMA_BRICK_STAIRS = REGISTRY.register("pink_chroma_brick_stairs", () -> new PinkChromaBrickStairsBlock());
	public static final RegistryObject<Block> PURPLE_CHROMA_BRICK_STAIRS = REGISTRY.register("purple_chroma_brick_stairs", () -> new PurpleChromaBrickStairsBlock());
	public static final RegistryObject<Block> RED_CHROMA_BRICK_STAIRS = REGISTRY.register("red_chroma_brick_stairs", () -> new RedChromaBrickStairsBlock());
	public static final RegistryObject<Block> YELLOW_CHROMA_BRICK_STAIRS = REGISTRY.register("yellow_chroma_brick_stairs", () -> new YellowChromaBrickStairsBlock());
	public static final RegistryObject<Block> INVERTED_BRICK_STAIRS = REGISTRY.register("inverted_brick_stairs", () -> new InvertedBrickStairsBlock());
	public static final RegistryObject<Block> BLUE_INVERTED_BRICK_STAIRS = REGISTRY.register("blue_inverted_brick_stairs", () -> new BlueInvertedBrickStairsBlock());
	public static final RegistryObject<Block> BROWN_INVERTED_BRICK_STAIRS = REGISTRY.register("brown_inverted_brick_stairs", () -> new BrownInvertedBrickStairsBlock());
	public static final RegistryObject<Block> CYAN_INVERTED_BRICK_STAIRS = REGISTRY.register("cyan_inverted_brick_stairs", () -> new CyanInvertedBrickStairsBlock());
	public static final RegistryObject<Block> GRAY_INVERTED_BRICK_STAIRS = REGISTRY.register("gray_inverted_brick_stairs", () -> new GrayInvertedBrickStairsBlock());
	public static final RegistryObject<Block> GREEN_INVERTED_BRICK_STAIRS = REGISTRY.register("green_inverted_brick_stairs", () -> new GreenInvertedBrickStairsBlock());
	public static final RegistryObject<Block> MAGENTA_INVERTED_BRICK_STAIRS = REGISTRY.register("magenta_inverted_brick_stairs", () -> new MagentaInvertedBrickStairsBlock());
	public static final RegistryObject<Block> ORANGE_INVERTED_BRICK_STAIRS = REGISTRY.register("orange_inverted_brick_stairs", () -> new OrangeInvertedBrickStairsBlock());
	public static final RegistryObject<Block> PINK_INVERTED_BRICK_STAIRS = REGISTRY.register("pink_inverted_brick_stairs", () -> new PinkInvertedBrickStairsBlock());
	public static final RegistryObject<Block> PURPLE_INVERTED_BRICK_STAIRS = REGISTRY.register("purple_inverted_brick_stairs", () -> new PurpleInvertedBrickStairsBlock());
	public static final RegistryObject<Block> RED_INVERTED_BRICK_STAIRS = REGISTRY.register("red_inverted_brick_stairs", () -> new RedInvertedBrickStairsBlock());
	public static final RegistryObject<Block> YELLOW_INVERTED_BRICK_STAIRS = REGISTRY.register("yellow_inverted_brick_stairs", () -> new YellowInvertedBrickStairsBlock());
	public static final RegistryObject<Block> SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("small_chroma_brick_stairs", () -> new SmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> BLUE_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("blue_small_chroma_brick_stairs", () -> new BlueSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> BROWN_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("brown_small_chroma_brick_stairs", () -> new BrownSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> CYAN_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("cyan_small_chroma_brick_stairs", () -> new CyanSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> GRAY_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("gray_small_chroma_brick_stairs", () -> new GraySmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> GREEN_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("green_small_chroma_brick_stairs", () -> new GreenSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> MAGENTA_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("magenta_small_chroma_brick_stairs", () -> new MagentaSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> ORANGE_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("orange_small_chroma_brick_stairs", () -> new OrangeSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> PINK_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("pink_small_chroma_brick_stairs", () -> new PinkSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> PURPLE_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("purple_small_chroma_brick_stairs", () -> new PurpleSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> RED_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("red_small_chroma_brick_stairs", () -> new RedSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> YELLOW_SMALL_CHROMA_BRICK_STAIRS = REGISTRY.register("yellow_small_chroma_brick_stairs", () -> new YellowSmallChromaBrickStairsBlock());
	public static final RegistryObject<Block> SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("small_inverted_brick_stairs", () -> new SmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> BLUE_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("blue_small_inverted_brick_stairs", () -> new BlueSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> BROWN_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("brown_small_inverted_brick_stairs", () -> new BrownSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> CYAN_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("cyan_small_inverted_brick_stairs", () -> new CyanSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> GRAY_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("gray_small_inverted_brick_stairs", () -> new GraySmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> GREEN_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("green_small_inverted_brick_stairs", () -> new GreenSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> MAGENTA_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("magenta_small_inverted_brick_stairs", () -> new MagentaSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> ORANGE_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("orange_small_inverted_brick_stairs", () -> new OrangeSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> PINK_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("pink_small_inverted_brick_stairs", () -> new PinkSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> PURPLE_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("purple_small_inverted_brick_stairs", () -> new PurpleSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> RED_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("red_small_inverted_brick_stairs", () -> new RedSmallInvertedBrickStairsBlock());
	public static final RegistryObject<Block> YELLOW_SMALL_INVERTED_BRICK_STAIRS = REGISTRY.register("yellow_small_inverted_brick_stairs", () -> new YellowSmallInvertedBrickStairsBlock());
}
