
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.croma.mod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.croma.mod.CromamodMod;

public class CromamodModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, CromamodMod.MODID);
	public static final RegistryObject<Item> BLUE_CHROMA_TILE = block(CromamodModBlocks.BLUE_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CHROMA_TILE = block(CromamodModBlocks.CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_CHROMA_TILE = block(CromamodModBlocks.BROWN_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_CHROMA_TILE = block(CromamodModBlocks.CYAN_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_CHROMA_TILE = block(CromamodModBlocks.GRAY_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_CHROMA_TILE = block(CromamodModBlocks.GREEN_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_CHROMA_TILE = block(CromamodModBlocks.MAGENTA_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_CHROMA_TILE = block(CromamodModBlocks.ORANGE_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_CHROMA_TILE = block(CromamodModBlocks.PINK_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_CHROMA_TILE = block(CromamodModBlocks.PURPLE_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_CHROMA_TILE = block(CromamodModBlocks.RED_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_CHROMA_TILE = block(CromamodModBlocks.YELLOW_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> INVERTED_TILE = block(CromamodModBlocks.INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_INVERTED_TILE = block(CromamodModBlocks.BLUE_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_INVERTED_TILE = block(CromamodModBlocks.BROWN_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_INVERTED_TILE = block(CromamodModBlocks.CYAN_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_INVERTED_TILE = block(CromamodModBlocks.GRAY_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_INVERTED_TILE = block(CromamodModBlocks.GREEN_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_INVERTED_TILE = block(CromamodModBlocks.MAGENTA_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_INVERTED_TILE = block(CromamodModBlocks.ORANGE_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_INVERTED_TILE = block(CromamodModBlocks.PINK_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_INVERTED_TILE = block(CromamodModBlocks.PURPLE_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_INVERTED_TILE = block(CromamodModBlocks.RED_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_INVERTED_TILE = block(CromamodModBlocks.YELLOW_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CUT_CHROMA_TILE = block(CromamodModBlocks.CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_CUT_CHROMA_TILE = block(CromamodModBlocks.BLUE_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_CUT_CHROMA_TILE = block(CromamodModBlocks.BROWN_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_CUT_CHROMA_TILE = block(CromamodModBlocks.CYAN_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_CUT_CHROMA_TILE = block(CromamodModBlocks.GRAY_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_CUT_CHROMA_TILE = block(CromamodModBlocks.GREEN_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_CUT_CHROMA_TILE = block(CromamodModBlocks.MAGENTA_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_CUT_CHROMA_TILE = block(CromamodModBlocks.ORANGE_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_CUT_CHROMA_TILE = block(CromamodModBlocks.PINK_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_CUT_CHROMA_TILE = block(CromamodModBlocks.PURPLE_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_CUT_CHROMA_TILE = block(CromamodModBlocks.RED_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_CUT_CHROMA_TILE = block(CromamodModBlocks.YELLOW_CUT_CHROMA_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CUT_INVERTED_TILE = block(CromamodModBlocks.CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_CUT_INVERTED_TILE = block(CromamodModBlocks.BLUE_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_CUT_INVERTED_TILE = block(CromamodModBlocks.BROWN_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_CUT_INVERTED_TILE = block(CromamodModBlocks.CYAN_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_CUT_INVERTED_TILE = block(CromamodModBlocks.GRAY_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_CUT_INVERTED_TILE = block(CromamodModBlocks.GREEN_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTE_CUT_INVERTED_TILE = block(CromamodModBlocks.MAGENTE_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_CUT_INVERTED_TILE = block(CromamodModBlocks.ORANGE_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_CUT_INVERTED_TILE = block(CromamodModBlocks.PINK_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_CUT_INVERTED_TILE = block(CromamodModBlocks.PURPLE_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_CUT_INVERTED_TILE = block(CromamodModBlocks.RED_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_CUT_INVERTED_TILE = block(CromamodModBlocks.YELLOW_CUT_INVERTED_TILE, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CHROMA_SLAB = block(CromamodModBlocks.CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_CHROMA_SLAB = block(CromamodModBlocks.BLUE_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_CHROMA_SLAB = block(CromamodModBlocks.BROWN_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_CHROMA_SLAB = block(CromamodModBlocks.CYAN_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_CHROMA_SLAB = block(CromamodModBlocks.GRAY_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_CHROMA_SLAB = block(CromamodModBlocks.GREEN_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_CHROMA_SLAB = block(CromamodModBlocks.MAGENTA_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_CHROMA_SLAB = block(CromamodModBlocks.ORANGE_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_CHROMA_SLAB = block(CromamodModBlocks.PINK_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_CHROMA_SLAB = block(CromamodModBlocks.PURPLE_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_CHROMA_SLAB = block(CromamodModBlocks.RED_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_CHROMA_SLAB = block(CromamodModBlocks.YELLOW_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CUT_CHROMA_SLAB = block(CromamodModBlocks.CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_CUT_CHROMA_SLAB = block(CromamodModBlocks.BLUE_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_CUT_CHROMA_SLAB = block(CromamodModBlocks.BROWN_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_CUT_CHROMA_SLAB = block(CromamodModBlocks.CYAN_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_CUT_CHROMA_SLAB = block(CromamodModBlocks.GRAY_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_CUT_CHROMA_SLAB = block(CromamodModBlocks.GREEN_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_CUT_CHROMA_SLAB = block(CromamodModBlocks.MAGENTA_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_CUT_CHROMA_SLAB = block(CromamodModBlocks.ORANGE_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_CUT_CHROMA_SLAB = block(CromamodModBlocks.PINK_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_CUT_CHROMA_SLAB = block(CromamodModBlocks.PURPLE_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_CUT_CHROMA_SLAB = block(CromamodModBlocks.RED_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_CUT_CHROMA_SLAB = block(CromamodModBlocks.YELLOW_CUT_CHROMA_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_CUT_INVERTED_SLAB = block(CromamodModBlocks.BLUE_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_CUT_INVERTED_SLAB = block(CromamodModBlocks.BROWN_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> INVERTED_SLAB = block(CromamodModBlocks.INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_INVERTED_SLAB = block(CromamodModBlocks.BLUE_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_INVERTED_SLAB = block(CromamodModBlocks.BROWN_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_INVERTED_SLAB = block(CromamodModBlocks.CYAN_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_INVERTED_SLAB = block(CromamodModBlocks.GRAY_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_INVERTED_SLAB = block(CromamodModBlocks.GREEN_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_INVERTED_SLAB = block(CromamodModBlocks.MAGENTA_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_INVERTED_SLAB = block(CromamodModBlocks.ORANGE_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_INVERTED_SLAB = block(CromamodModBlocks.PINK_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_INVERTED_SLAB = block(CromamodModBlocks.PURPLE_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_INVERTED_SLAB = block(CromamodModBlocks.RED_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_INVERTED_SLAB = block(CromamodModBlocks.YELLOW_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_CUT_INVERTED_SLAB = block(CromamodModBlocks.CYAN_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CUT_INVERTED_SLAB = block(CromamodModBlocks.CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_CUT_INVERTED_SLAB = block(CromamodModBlocks.GRAY_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_CUT_INVERTED_SLAB = block(CromamodModBlocks.GREEN_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_CUT_INVERTED_SLAB = block(CromamodModBlocks.MAGENTA_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_CUT_INVERTED_SLAB = block(CromamodModBlocks.ORANGE_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_CUT_INVERTED_SLAB = block(CromamodModBlocks.PINK_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_CUT_INVERTED_SLAB = block(CromamodModBlocks.PURPLE_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_CUT_INVERTED_SLAB = block(CromamodModBlocks.RED_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_CUT_INVERTED_SLAB = block(CromamodModBlocks.YELLOW_CUT_INVERTED_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CHROMA_BRICK_SLAB = block(CromamodModBlocks.CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_CHROMA_BRICK_SLAB = block(CromamodModBlocks.BLUE_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_CHROMA_BRICK_SLAB = block(CromamodModBlocks.BROWN_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_CHROMA_BRICK_SLAB = block(CromamodModBlocks.CYAN_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_CHROMA_BRICK_SLAB = block(CromamodModBlocks.GRAY_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_CHROMA_BRICK_SLAB = block(CromamodModBlocks.GREEN_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_CHROMA_BRICK_SLAB = block(CromamodModBlocks.MAGENTA_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_CHROMA_BRICK_SLAB = block(CromamodModBlocks.ORANGE_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_CHROMA_BRICK_SLAB = block(CromamodModBlocks.PINK_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_CHROMA_BRICK_SLAB = block(CromamodModBlocks.PURPLE_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_CHROMA_BRICK_SLAB = block(CromamodModBlocks.RED_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_CHROMA_BRICK_SLAB = block(CromamodModBlocks.YELLOW_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> INVERTED_BRICK_SLAB = block(CromamodModBlocks.INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_INVERTED_BRICK_SLAB = block(CromamodModBlocks.BLUE_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_INVERTED_BRICK_SLAB = block(CromamodModBlocks.BROWN_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_INVERTED_BRICK_SLAB = block(CromamodModBlocks.CYAN_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_INVERTED_BRICK_SLAB = block(CromamodModBlocks.GRAY_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_INVERTED_BRICK_SLAB = block(CromamodModBlocks.GREEN_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_INVERTED_BRICK_SLAB = block(CromamodModBlocks.MAGENTA_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_INVERTED_BRICK_SLAB = block(CromamodModBlocks.ORANGE_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_INVERTED_BRICK_SLAB = block(CromamodModBlocks.PINK_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_INVERTED_BRICK_SLAB = block(CromamodModBlocks.PURPLE_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_INVERTED_BRICK_SLAB = block(CromamodModBlocks.RED_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_INVERTED_BRICK_SLAB = block(CromamodModBlocks.YELLOW_INVERTED_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CHROMA_BRICKS = block(CromamodModBlocks.CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_CHROMA_BRICKS = block(CromamodModBlocks.BLUE_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_CHROMA_BRICKS = block(CromamodModBlocks.BROWN_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_CHROMA_BRICKS = block(CromamodModBlocks.CYAN_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_CHROMA_BRICKS = block(CromamodModBlocks.GRAY_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_CHROMA_BRICKS = block(CromamodModBlocks.GREEN_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_CHROMA_BRICKS = block(CromamodModBlocks.MAGENTA_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_CHROMA_BRICKS = block(CromamodModBlocks.ORANGE_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_CHROMA_BRICKS = block(CromamodModBlocks.PINK_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_CHROMA_BRICKS = block(CromamodModBlocks.PURPLE_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_CHROMA_BRICKS = block(CromamodModBlocks.RED_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_CHROMA_BRICKS = block(CromamodModBlocks.YELLOW_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> INVERTED_BRICKS = block(CromamodModBlocks.INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_INVERTED_BRICKS = block(CromamodModBlocks.BLUE_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_INVERTED_BRICKS = block(CromamodModBlocks.BROWN_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_INVERTED_BRICKS = block(CromamodModBlocks.CYAN_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_INVERTED_BRICKS = block(CromamodModBlocks.GRAY_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_INVERTED_BRICKS = block(CromamodModBlocks.GREEN_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_INVERTED_BRICKS = block(CromamodModBlocks.MAGENTA_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_INVERTED_BRICKS = block(CromamodModBlocks.ORANGE_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_INVERTED_BRICKS = block(CromamodModBlocks.PINK_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_INVERTED_BRICKS = block(CromamodModBlocks.PURPLE_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_INVERTED_BRICKS = block(CromamodModBlocks.RED_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_INVERTED_BRICKS = block(CromamodModBlocks.YELLOW_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> SMALL_CHROMA_BRICKS = block(CromamodModBlocks.SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.BLUE_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.BROWN_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.CYAN_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.GRAY_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.GREEN_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.MAGENTA_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.ORANGE_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.PINK_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.PURPLE_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.RED_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_SMALL_CHROMA_BRICKS = block(CromamodModBlocks.YELLOW_SMALL_CHROMA_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> SMALL_INVERTED_BRICKS = block(CromamodModBlocks.SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BLUE_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.BLUE_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> BROWN_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.BROWN_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> CYAN_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.CYAN_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GRAY_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.GRAY_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> GREEN_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.GREEN_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> MAGENTA_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.MAGENTA_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> ORANGE_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.ORANGE_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PINK_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.PINK_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> PURPLE_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.PURPLE_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> RED_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.RED_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> YELLOW_SMALL_INVERTED_BRICKS = block(CromamodModBlocks.YELLOW_SMALL_INVERTED_BRICKS, CromamodModTabs.TAB_CHROMATIC_BUILDING_BLOCKS_TAB);
	public static final RegistryObject<Item> SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BLUE_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.BLUE_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> BROWN_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.BROWN_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> CYAN_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.CYAN_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GRAY_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.GRAY_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> GREEN_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.GREEN_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> MAGENTA_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.MAGENTA_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> ORANGE_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.ORANGE_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PINK_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.PINK_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> PURPLE_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.PURPLE_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> RED_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.RED_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);
	public static final RegistryObject<Item> YELLOW_SMALL_CHROMA_BRICK_SLAB = block(CromamodModBlocks.YELLOW_SMALL_CHROMA_BRICK_SLAB, CromamodModTabs.TAB_CHROMATIC_DECOR_TAB);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
